version: '3.8'

services:

  #Contenedor con base de datos
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db-catalogo

    environment:
      MYSQL_DATABASE: catalogo_db_test
      MYSQL_USER: catalogo_user_test
      MYSQL_ROOT_PASSWORD: DuocUc..2025
      MYSQL_PASSWORD: DuocUc..2025
    ports:
      - "3308:3306"
    networks:
      - externa

  catalogo-app: 
    build: .
    container_name: catalogo-app
    depends_on:
       - mysql-db
      
    ports: 
    - "8080:8080"
    environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/catalogo_db_test?useSSL=true&serverTimezone=UTC&hibernate.jdbc.batch_versioned_data=true
       SPRING_DATASOURCE_USERNAME: catalogo_user_test
       SPRING_DATASOURCE_PASSWORD: DuocUc..2025
       SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    networks:
      - externa 

networks:
  externa:
    external: true
    name: microservicioRed
